

    INSERT INTO `filieres` (`id`, `Intitule`, `type_diplome`) 
    VALUES
(102,"Éducateur Spécialisé en Petite Enfance",3),
(103," Commerce",3),
(104," Gestion des Entreprises",3),
(105,"Techniques de Secrétariat de Direction (TSD)",3),
(106," Finance et Comptabilité",3),
(107,"Traitement de Surface",3),
(108,"TS en Météorologie",3),
(109," Industrie Meunière",3),
(110," Emballage et Conditionnement",3),
(111," Fabrication Industrie Agroalimentaire",3),
(112," Oléiculture et Oléotechnie",3),
(113," Hygiène et Qualité",3),
(114," Maintenance en Industrie Agroalimentaire",3),
(115,"Infographie",3),
(116," Production Graphique",3),
(117," Audio Visuel (Option : Montage)",3),
(118," Audio Visuel (Option : Son)",3),
(119," Décors et Accessoires",3),
(120," Effets Spéciaux",3),
(121," Régie et Gestion de Production",3),
(122," Audio Visuel (Option : Image)",3),
(123," Génie Civil",3),
(124," Conducteur de Travaux : Travaux Publics",3),
(125," Gros Œuvres",3),
(126," Géomètre Topographe",3),
(127," Patrimoine Design",3),
(128," Bureau d’Etude en Construction Métallique",3),
(129," Chimie Cuir",3),
(130," Méthodes Cuir",3),
(131," Méthodes en Fabrication Mécanique",3),
(132," Thermique Industrielle",3),
(133," Génie Climatique",3),
(134,"Automatisation et Instrumentation Industrielle",3),
(135,"Electromécanique des Systèmes Automatisées",3),
(136,"Maintenance des Machines Outils et Autres Machines de Production Automatisée",3),
(137,"Mécatronique",3),
(138," Fabrication en Electronique",3),
(139,"Techniques des Réseaux Informatiques",3),
(140,"Techniques des Télécommunications",3),
(141,"Techniques de Développement Informatique",3),
(142,"Techniques de Développement Multimédia",3),
(143,"Prothésiste Dentaire",3),
(144,"Assistance Dentaire",3),
(145,"Chimie Industrielle",3),
(146,"Maintenance des Machines et Outillage en Plasturgie",3),
(147,"Transformation des Matériaux Composites",3),
(148,"Bureau D’Études Option Outillage de Presse",3),
(149,"Bureau d’Etudes en Automobile",3),
(150,"Technico-Commercial en Vente de Véhicules et Pièces de Rechange",3),
(151,"Diagnostic et Electronique Embarquée",3),
(152,"Production et Qualité en Automobile",3),
(153,"Gestion d’entreprise équine",3),
(154,"Qualité et Contrôle Textile",3),
(155,"Techniques d’Habillement Industrialisation",3),
(156,"Maintenance et Production Textile",3),
(157,"Animation Touristique",3),
(158,"Gestion Hôtelière",3),
(159,"Agences de Voyages",3),
(160,"Hébergement et Réception",3),
(161,"Responsable d’Exploitation Logistique",3),
(162,"Exploitation en Transport",3),
(163,"Logistique Aéroportuaire",3),
(164,"Usinage sur MOCN option METHODE FAO Outillage de presse",3),
(165,"Usinage Sur MOCN Option Usinage Outillage de Presse",3),
(166,"Méthode, Production et Qualité option Automobile",3),